name: Deploy app to EC2 instance

on:
    push:
        branches: [ workflow-deploy-app, dev, main ]

jobs:
    build_docker_image:
        runs-on: ubuntu-latest
        outputs:
            image_tag: ${{ steps.compute_tag.outputs.image_tag }}
            registry:  ${{ steps.login_ecr.outputs.registry }}
            
        steps: 
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup AWS credentials
              uses: aws-actions/configure-aws-credentials@v5
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{secrets.AWS_REGION}}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - id: compute-tag
              run: |
                if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
                  TAG="${GITHUB_REF_NAME}"
                else
                  TAG="${GITHUB_REF_NAME}"           
                fi
                echo "image_tag=$TAG" >> "$GITHUB_OUTPUT"
        
            - name: Build, tag, and push docker image to Amazon ECR
              env:
                REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                REPOSITORY: ${{ secrets.AWS_ECR_REPO }}
              run: |
                chmod +x .github/docker_image_tagging.sh
                ./.github/docker_image_tagging.sh

    deploy_dockerized_app:
        needs: build_docker_image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Copy files to EC2
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER_NAME }}
                key: ${{ secrets.EC2_SSH_KEY }}
                source: "docker/docker-compose.yml,.env.example"
                target: "/home/ubuntu/app"
            
            - name: Deploy to EC2
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER_NAME }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                    cd /home/ubuntu/app

                    cp .env.example .env
                    cat >> .env <<EOF
                    REGISTRY=${{ needs.build_docker_image.outputs.registry }}
                    REPOSITORY=${{ secrets.AWS_ECR_REPO }}
                    IMAGE_TAG=${{ needs.build_docker_image.outputs.image_tag }}
                    EOF

                    aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
                    | docker login --username AWS --password-stdin ${{ needs.build_docker_image.outputs.registry }}

                    docker compose -f docker/docker-compose.yml pull
                    docker compose -f docker/docker-compose.yml up -d
